version: '3'
services:
  web:
    image: jldiazb16/server_id_web
    env_file: .env
    depends_on:
      - api
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
    networks:
      - roachnet

  api:
    image: jldiazb16/server_id_api
    env_file: .env
    command: /go/bin/api
    ports:
      - 3000:3000
    depends_on:
      - roach1
      - roach2
      - roach3
    networks:
      - roachnet

  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:v19.1.1
    command: start --insecure
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - cockroach_data1:/cockroach/cockroach-data
    networks:
      roachnet:
        aliases:
          - roach1

  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:v19.1.1
    command: start --insecure --join=roach1
    volumes:
      - cockroach_data2:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      roachnet:
        aliases:
          - roach2

  roach3:
    container_name: roach3
    image: cockroachdb/cockroach:v19.1.1
    command: start --insecure --join=roach1
    volumes:
      - cockroach_data3:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      roachnet:
        aliases:
          - roach3

  db_init:
    image: cockroachdb/cockroach:v19.1.1
    depends_on:
      - roach2
    volumes:
      - ./setup/setup_db.sh:/setup_db.sh
      - ./setup/create_db.sql:/create_db.sql
    entrypoint: "/bin/bash"
    command: /setup_db.sh
    networks:
      - roachnet

networks:
  roachnet:
    driver: bridge

volumes:
  cockroach_data1:
    driver: local
  cockroach_data2:
    driver: local
  cockroach_data3:
    driver: local
