version: '3'

services:
  web:
    build: .
    command: "./server_id_api"
    volumes:
      - ./:/go/src/server_id_api
    ports:
      - 3000:3000
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
